# site settings
title: Luke Hollomon - Science Tutor
subtitle: Tutoring science and exam prep, online and in person.
email: lukehollomon@gmail.com
description: A science teacher and tutor in the DC area, specializing in exam prep and advanced science courses. Tutoring from middle school up to medical school.
baseurl: "forty-jekyll-theme-tutor/"
url: ""
# homepage tiles
tiles-source: "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
instagram_url: https://instagram.com
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed
